freebsd_instance:
  image: freebsd-12-0-release-amd64

test_task:
  install_script:
    - pkg update
    - pkg install -y gmake pcre2 libunwind llvm70 git
  env:
    matrix:
      CONFIG: debug
      CONFIG: release
  test_script:
    - gmake all config=$CONFIG -j3 default_ssl=openssl_1.1.0
    - gmake test-ci config=$CONFIG default_ssl=openssl_1.1.0
