# Nightly stress tests using string-message-passewr
task:
  only_if: $CIRRUS_CRON == "stress"

  timeout_in: 120m

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.3

  matrix:
    - name: "Stress Test: arm64 macos monterey [release]"
      environment:
        TARGET: test-stress-release
    - name: "Stress Test: arm64 macos monterey [debug]"
      environment:
        TARGET: test-stress-debug
      depends_on:
        - "Stress Test: arm64 macos monterey [release]"
    - name: "Stress Test: arm64 macos monterey [cd] [release]"
      environment:
        TARGET: test-stress-with-cd-release
    - name: "Stress Test: arm64 macos monterey [cd] [debug]"
      environment:
        TARGET: test-stress-with-cd-debug
      depends_on:
        - "Stress Test: arm64 macos monterey [cd] [release]"

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 Makefile` `md5 CMakeLists.txt` `md5 lib/CMakeLists.txt` arm64 ghcr.io/cirruslabs/macos-ventura-xcode:14.3 20220511"
    populate_script: make libs build_flags=-j12
  upload_caches:
    - libs

  configure_script:
    - make configure arch=armv8 config=debug
  build_script:
    - make build config=debug
  stress_test_script:
    - make ${TARGET} config=debug usedebugger=lldb
