task:
  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191105
    cpu: 8
    memory: 24

  name: "lib/llvm: x86-64-unknown-linux-gnu"

  test_script:
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release -j8
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release test-ci

  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release'

task:
  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20191105
    cpu: 8
    memory: 24

  name: "lib/llvm: x86-64-unknown-linux-musl"

  test_script:
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release link=static -j8
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release link=static test-ci

  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release'

task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
    cpu: 8
    memory: 24

  name: "lib/llvm: x86-64-unknown-freebsd12.0"

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y cmake gmake libunwind git

  test_script:
    - gmake -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release -j8
    - gmake -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release test-ci

  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release'

task:
  osx_instance:
    image: mojave-xcode-11.2.1

  name: "lib/llvm: macOS"

  install_script:
    - brew install coreutils

  test_script:
    - export CC1=clang
    - export CXX1=clang++
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release -j8
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release test-ci

  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release'
