task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64

  name: "freebsd-12-release"
  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y gmake pcre2 libunwind llvm70 git

  test_script:
    - LLVM_CONFIG=llvm-config70 gmake all config=release -j3 default_ssl=openssl_1.1.0
    - LLVM_CONFIG=llvm-config70 gmake test-ci config=release default_ssl=openssl_1.1.0
