#
# Nightly build tasks
#

task:
  only_if: $CIRRUS_CRON == "nightly"

  matrix:
    - name: "nightly: x86-64-unknown-linux-rocky8"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-rocky8-builder:20210707
      environment:
        CACHE_BUSTER: 20210707
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-rocky8
    - name: "nightly: x86-64-unknown-linux-centos8"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-centos8-builder:20210225
      environment:
        CACHE_BUSTER: 20210225
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-centos8
    - name: "nightly: x86-64-unknown-linux-gnu"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20200423
      environment:
        CACHE_BUSTER: 20210224
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-gnu
    - name: "nightly: x86-64-unknown-linux-ubuntu18.04"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu18.04-builder:20210714
      environment:
        CACHE_BUSTER: 20210714
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-ubuntu18.04
    - name: "nightly: x86-64-unknown-linux-ubuntu20.04"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu20.04-builder:20200830
      environment:
        CACHE_BUSTER: 20210224
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-ubuntu20.04
    - name: "nightly: x86-64-unknown-linux-ubuntu21.04"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu21.04-builder:20210920
      environment:
        CACHE_BUSTER: 20210920
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-ubuntu21.04
    - name: "nightly: x86-64-unknown-linux-musl"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20210420
      environment:
        CACHE_BUSTER: 20210224
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-musl

  container:
    cpu: 8
    memory: 24

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - echo "`md5sum lib/CMakeLists.txt` ${TRIPLE_VENDOR}-${TRIPLE_OS} ${CACHE_BUSTER}"
    populate_script: make libs build_flags=-j8
  upload_caches:
    - libs

  nightly_script:
    - bash .ci-scripts/x86-64-nightly.bash

task:
  only_if: $CIRRUS_CRON == "nightly"

  freebsd_instance:
    image: freebsd-13-0-release-amd64
    cpu: 8
    memory: 24

  name: "nightly: x86-64-unknown-freebsd-13.0"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - echo "IGNORE_OSVERSION = yes" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y bash cmake gmake libunwind git py38-pip
    - pip install --upgrade cloudsmith-cli

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 lib/CMakeLists.txt` freebsd-13.0 20210710"
    populate_script: gmake libs arch=x86-64 build_flags=-j8
  upload_caches:
    - libs

  nightly_script:
    - bash .ci-scripts/x86-64-unknown-freebsd-13.0-nightly.bash

task:
  only_if: $CIRRUS_CRON == "nightly"

  osx_instance:
    image: big-sur-xcode-12.5

  name: "nightly: x86-64-apple-darwin"

  environment:
    TRIPLE_VENDOR: apple
    TRIPLE_OS: darwin
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 lib/CMakeLists.txt` macos big-sur-xcode-12.5 20210710"
    populate_script: make libs build_flags=-j8
  upload_caches:
    - libs

  install_script:
    - brew install coreutils python
    - pip3 install --upgrade cloudsmith-cli

  nightly_script:
    - export TZ=utc
    - bash .ci-scripts/x86-64-nightly.bash

task:
  only_if: $CIRRUS_CRON == "nightly"

  windows_container:
    image: ponylang/ponyc-ci-x86-64-pc-windows-msvc-builder:20210430
    os_version: 2019
    cpu: 8
    memory: 24

  name: "nightly: x86-64-pc-windows-msvc"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - ps: (Get-FileHash -Path lib\CMakeLists.txt).Hash + "Windows 20210430"
    populate_script:
      - ps: .\make.ps1 -Command libs -Generator "Visual Studio 16 2019"
  upload_caches:
    - libs

  config_script:
    - ps: .\make.ps1 -Command configure -Config Release -Generator "Visual Studio 16 2019" -Prefix "build\install\release" -Version nightly
  build_script:
    - ps: .\make.ps1 -Command build -Config Release -Generator "Visual Studio 16 2019" -Prefix "build\install\release" -Version nightly
  install_script:
    - ps: .\make.ps1 -Command install -Config Release -Prefix "build\install\release"
  package_script:
    - ps: .\make.ps1 -Command package -Config Release -Prefix "build\install\release" -Version nightly
  upload_script:
    - ps: $version = (Get-Date).ToString("yyyyMMdd"); cloudsmith push raw --version $version --api-key $env:CLOUDSMITH_API_KEY --summary "Pony compiler" --description "https://github.com/ponylang/ponyc" ponylang/nightlies build\ponyc-x86-64-pc-windows-msvc.zip

#
# Release build tasks
#

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  matrix:
    - name: "release: x86-64-unknown-linux-rocky8"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-rocky8-builder:20210707
      environment:
        CACHE_BUSTER: 20210707
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-rocky8
    - name: "release: x86-64-unknown-linux-centos8"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-centos8-builder:20210225
      environment:
        CACHE_BUSTER: 20210225
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-centos8
    - name: "release: x86-64-unknown-linux-gnu"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20200423
      environment:
        CACHE_BUSTER: 20200423
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-gnu
    - name: "release: x86-64-unknown-linux-ubuntu18.04"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu18.04-builder:20210714
      environment:
        CACHE_BUSTER: 20210714
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-ubuntu18.04
    - name: "release: x86-64-unknown-linux-ubuntu20.04"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu20.04-builder:20200830
      environment:
        CACHE_BUSTER: 20200830
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-ubuntu20.04
    - name: "release: x86-64-unknown-linux-ubuntu21.04"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu21.04-builder:20210920
      environment:
        CACHE_BUSTER: 20210920
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-ubuntu21.04
    - name: "release: x86-64-unknown-linux-musl"
      container:
        image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20210420
      environment:
        CACHE_BUSTER: 20200421
        TRIPLE_VENDOR: unknown
        TRIPLE_OS: linux-musl

  container:
    cpu: 8
    memory: 24

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - echo "`md5sum lib/CMakeLists.txt` ${TRIPLE_VENDOR}-${TRIPLE_OS} ${CACHE_BUSTER}"
    populate_script: make libs build_flags=-j8
  upload_caches:
    - libs

  release_script:
    - bash .ci-scripts/x86-64-release.bash

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  freebsd_instance:
    image: freebsd-13-0-release-amd64
    cpu: 8
    memory: 24

  name: "release: x86-64-unknown-freebsd-13.0"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - echo "IGNORE_OSVERSION = yes" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y bash cmake gmake libunwind git py38-pip
    - pip install --upgrade cloudsmith-cli

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 lib/CMakeLists.txt` freebsd-13.0 20210710"
    populate_script: gmake libs arch=x86-64 build_flags=-j8
  upload_caches:
    - libs

  release_script:
    - bash .ci-scripts/x86-64-unknown-freebsd-13.0-release.bash

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  osx_instance:
    image: big-sur-xcode-12.5

  name: "release: x86-64-apple-darwin"

  environment:
    TRIPLE_VENDOR: apple
    TRIPLE_OS: darwin
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 lib/CMakeLists.txt` macos big-sur-xcode-12.5 20210710"
    populate_script: make libs build_flags=-j8
  upload_caches:
    - libs

  install_script:
    - brew install coreutils python
    - pip3 install --upgrade cloudsmith-cli

  release_script:
    - export TZ=utc
    - bash .ci-scripts/x86-64-release.bash

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'

  windows_container:
    image: ponylang/ponyc-ci-x86-64-pc-windows-msvc-builder:20210430
    os_version: 2019
    cpu: 8
    memory: 24

  name: "release: x86-64-pc-windows-msvc"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - ps: (Get-FileHash -Path lib\CMakeLists.txt).Hash + "Windows 20210430"
    populate_script:
      - ps: .\make.ps1 -Command libs -Generator "Visual Studio 16 2019"
  upload_caches:
    - libs

  config_script:
    - ps: .\make.ps1 -Command configure -Config Release -Generator "Visual Studio 16 2019" -Prefix "build\install\release" -Version (Get-Content .\VERSION)
  build_script:
    - ps: .\make.ps1 -Command build -Config Release -Generator "Visual Studio 16 2019" -Prefix "build\install\release" -Version (Get-Content .\VERSION)
  install_script:
    - ps: .\make.ps1 -Command install -Config Release -Prefix "build\install\release"
  package_script:
    - ps: .\make.ps1 -Command package -Config Release -Prefix "build\install\release" -Version (Get-Content .\VERSION)
  upload_script:
    - ps: $version = (Get-Content .\VERSION); cloudsmith push raw --version $version --api-key $env:CLOUDSMITH_API_KEY --summary "Pony compiler" --description "https://github.com/ponylang/ponyc" ponylang/releases build\ponyc-x86-64-pc-windows-msvc.zip

# Nightly stress tests using message-ubench
task:
  only_if: $CIRRUS_CRON == "stress"

  matrix:
  - name: "Stress Test: x86-64-unknown-linux-ubuntu20.04 [release]"
    container:
      image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu20.04-builder:20200830
    environment:
      CACHE_BUSTER: 20210224
      TRIPLE_VENDOR: unknown
      TRIPLE_OS: linux-ubuntu20.04
      TARGET: test-stress-release
  - name: "Stress Test: x86-64-unknown-linux-ubuntu20.04 [debug]"
    container:
      image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu20.04-builder:20200830
    environment:
      CACHE_BUSTER: 20210224
      TRIPLE_VENDOR: unknown
      TRIPLE_OS: linux-ubuntu20.04
      TARGET: test-stress-debug
    depends_on:
      - "Stress Test: x86-64-unknown-linux-ubuntu20.04 [release]"
  - name: "Stress Test: x86-64-unknown-linux-musl [release]"
    container:
      image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20210420
    environment:
      CACHE_BUSTER: 20210224
      TRIPLE_VENDOR: unknown
      TRIPLE_OS: linux-musl
      TARGET: test-stress-release
  - name: "Stress Test: x86-64-unknown-linux-musl [debug]"
    container:
      image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20210420
    environment:
      CACHE_BUSTER: 20210224
      TRIPLE_VENDOR: unknown
      TRIPLE_OS: linux-musl
      TARGET: test-stress-debug
    depends_on:
      - "Stress Test: x86-64-unknown-linux-musl [release]"

  container:
    cpu: 8
    memory: 24

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - echo "`md5sum lib/CMakeLists.txt` ${TRIPLE_VENDOR}-${TRIPLE_OS} ${CACHE_BUSTER} stress"
    populate_script: make libs build_flags=-j8
  upload_caches:
    - libs

  configure_script:
    - make configure config=debug
  build_script:
    - make build config=debug
  stress_test_script:
    - make ${TARGET} config=debug

task:
  only_if: $CIRRUS_CRON == "stress"

  arm_container:
    image: ponylang/ponyc-ci-aarch64-unknown-linux-ubuntu20.04-builder:20211003
    cpu: 8
    memory: 24

  matrix:
    - name: "Stress Test: aarch64-unknown-linux-ubuntu20.04 [release]"
      environment:
        TARGET: test-stress-release
    - name: "Stress Test: aarch64-unknown-linux-ubuntu20.04 [debug]"
      environment:
        TARGET: test-stress-debug
      depends_on:
        - "Stress Test: aarch64-unknown-linux-ubuntu20.04 [release]"

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5sum lib/CMakeLists.txt` aarch64-linux-gnu 20211003 stress"
    populate_script: make libs arch=armv8-a build_flags=-j8
  upload_caches:
    - libs

  configure_script:
    - make configure arch=armv8-a config=debug
  build_script:
    - make build arch=armv8-a config=debug
  stress_test_script:
    - make ${TARGET} arch=armv8-a config=debug
