task:
  container:
    image: ponylang/ponyc-ci:nightlies
    cpu: 8
    memory: 24

  name: "linux gnu release builder"

  clone_script: |
    if [ -n "$CIRRUS_TAG" ]
    then
      echo "cloning for tag $CIRRUS_TAG"
      git clone --depth 1 --branch "$CIRRUS_TAG" --recurse-submodules https://github.com/ponylang/ponyc.git
    elif [ -n "$CIRRUS_BRANCH" ]
    then
      echo "cloning for branch $CIRRUS_BRANCH"
      git clone --depth 1 --branch "$CIRRUS_BRANCH" --recurse-submodules https://github.com/ponylang/ponyc.git
    fi

  test_script:
    - cd ponyc
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 use=llvm_link_static -j4 prefix=/tmp/pony/ symlink=no install
    - tar -cf /tmp/ponyc.tar /tmp/pony/lib/pony/*
    - gzip /tmp/ponyc.tar
    - cloudsmith push raw --version 20190723 --k 1cc732891a064c6542e3632a6ee281b69dbdce18 main-pony/pony-nightlies /tmp/ponyc.tar.gz
