task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64

  name: "freebsd-12"
  install_script:
    - pkg update
    - pkg install -y gmake pcre2 libunwind llvm70 git
  env:
    matrix:
      CONFIG: debug
      CONFIG: release
  test_script:
    - gmake all config=$CONFIG -j3 default_ssl=openssl_1.1.0
    - gmake test-ci config=$CONFIG default_ssl=openssl_1.1.0

task:
  name: "cross-llvm-701-debug-arm"

  container:
    image: ponylang/ponyc-ci:cross-llvm-7.0.1-arm

  test_script:
    # build and test for x86_64 first
    - make config=debug verbose=1 -j3 all
    - make config=debug verbose=1 test-ci
    # build libponyrt for target arch
    - make config=debug verbose=1 CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++ arch=armv7-a tune=cortex-a9 bits=32 CFLAGS="-idirafter /usr/cross/include/" CXXFLAGS="-idirafter /usr/cross/include/" LDFLAGS="-idirafter /usr/cross/include/" PONYPATH=/usr/cross/lib -j3 libponyrt
    # build ponyc for target cross compilation
    - make config=debug verbose=1 PONYPATH=/usr/cross/lib cross_triple=arm-unknown-linux-gnueabi cross_arch=armv7-a cross_cpu=cortex-a9 cross_linker=arm-linux-gnueabi-gcc QEMU_RUNNER="qemu-arm-static --cpu cortex-a9 -L /usr/local/arm-linux-gnueabi/libc" -j3 all
    # run tests for cross built stdlib using ponyc cross building support
    - make config=debug verbose=1 PONYPATH=/usr/cross/lib cross_triple=arm-unknown-linux-gnueabi cross_arch=armv7-a cross_cpu=cortex-a9 cross_linker=arm-linux-gnueabi-gcc QEMU_RUNNER="qemu-arm-static --cpu cortex-a9 -L /usr/local/arm-linux-gnueabi/libc" test-cross-ci
