#
# Pull Request Tasks
#

task:
  only_if: $CIRRUS_PR != ''

  timeout_in: 120m

  windows_container:
    image: ponylang/ponyc-ci-x86-64-pc-windows-msvc-builder:20220803
    os_version: 2019
    cpu: 8
    memory: 24

  name: "x86-64 Windows MSVC"

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - ps: (Get-FileHash -Path make.ps1).Hash + (Get-FileHash -Path CMakeLists.txt).Hash + (Get-FileHash -Path lib\CMakeLists.txt).Hash + "Windows 20220803"
    populate_script:
      - ps: .\make.ps1 -Command libs -Generator "Visual Studio 17 2022"
  upload_caches:
    - libs

  debug_config_script:
    - ps: .\make.ps1 -Command configure -Config Debug -Generator "Visual Studio 17 2022"
  debug_build_script:
    - ps: .\make.ps1 -Command build -Config Debug
  debug_test_script:
    - ps: .\make.ps1 -Command test -Config Debug -Uselldb yes
  release_config_script:
    - ps: .\make.ps1 -Command configure -Config Release
  release_build_script:
    - ps: .\make.ps1 -Command build -Config Release
  release_test_script:
    - ps: .\make.ps1 -Command test -Config Release -Uselldb yes

#
# Nightly build tasks
#

task:
  only_if: $CIRRUS_CRON == "nightly"

  timeout_in: 120m

  windows_container:
    image: ponylang/ponyc-ci-x86-64-pc-windows-msvc-builder:20220803
    os_version: 2019
    cpu: 8
    memory: 24

  name: "nightly: x86-64-pc-windows-msvc"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - ps: (Get-FileHash -Path make.ps1).Hash + (Get-FileHash -Path CMakeLists.txt).Hash + (Get-FileHash -Path lib\CMakeLists.txt).Hash + "Windows 20220803"
    populate_script:
      - ps: .\make.ps1 -Command libs -Generator "Visual Studio 17 2022"
  upload_caches:
    - libs

  config_script:
    - ps: .\make.ps1 -Command configure -Config Release -Generator "Visual Studio 17 2022" -Prefix "build\install\release" -Version nightly
  build_script:
    - ps: .\make.ps1 -Command build -Config Release -Prefix "build\install\release" -Version nightly
  install_script:
    - ps: .\make.ps1 -Command install -Config Release -Prefix "build\install\release"
  package_script:
    - ps: .\make.ps1 -Command package -Config Release -Prefix "build\install\release" -Version nightly
  upload_script:
    - ps: $version = (Get-Date).ToString("yyyyMMdd"); cloudsmith push raw --version $version --api-key $env:CLOUDSMITH_API_KEY --summary "Pony compiler" --description "https://github.com/ponylang/ponyc" ponylang/nightlies build\ponyc-x86-64-pc-windows-msvc.zip

#
# Release build tasks
#

task:
  only_if: $CIRRUS_TAG =~ '^\d+\.\d+\.\d+$'
  use_compute_credits: true

  timeout_in: 120m

  windows_container:
    image: ponylang/ponyc-ci-x86-64-pc-windows-msvc-builder:20220803
    os_version: 2019
    cpu: 8
    memory: 24

  name: "release: x86-64-pc-windows-msvc"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - ps: (Get-FileHash -Path make.ps1).Hash + (Get-FileHash -Path CMakeLists.txt).Hash + (Get-FileHash -Path lib\CMakeLists.txt).Hash + "Windows 20220803"
    populate_script:
      - ps: .\make.ps1 -Command libs -Generator "Visual Studio 17 2022"
  upload_caches:
    - libs

  config_script:
    - ps: .\make.ps1 -Command configure -Config Release -Generator "Visual Studio 17 2022" -Prefix "build\install\release" -Version (Get-Content .\VERSION)
  build_script:
    - ps: .\make.ps1 -Command build -Config Release -Prefix "build\install\release" -Version (Get-Content .\VERSION)
  install_script:
    - ps: .\make.ps1 -Command install -Config Release -Prefix "build\install\release"
  package_script:
    - ps: .\make.ps1 -Command package -Config Release -Prefix "build\install\release" -Version (Get-Content .\VERSION)
  upload_script:
    - ps: $version = (Get-Content .\VERSION); cloudsmith push raw --version $version --api-key $env:CLOUDSMITH_API_KEY --summary "Pony compiler" --description "https://github.com/ponylang/ponyc" ponylang/releases build\ponyc-x86-64-pc-windows-msvc.zip

# Nightly stress tests using string-message-passewr
task:
  only_if: $CIRRUS_CRON == "stress"

  timeout_in: 120m

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.3

  matrix:
    - name: "Stress Test: arm64 macos monterey [release]"
      environment:
        TARGET: test-stress-release
    - name: "Stress Test: arm64 macos monterey [debug]"
      environment:
        TARGET: test-stress-debug
      depends_on:
        - "Stress Test: arm64 macos monterey [release]"
    - name: "Stress Test: arm64 macos monterey [cd] [release]"
      environment:
        TARGET: test-stress-with-cd-release
    - name: "Stress Test: arm64 macos monterey [cd] [debug]"
      environment:
        TARGET: test-stress-with-cd-debug
      depends_on:
        - "Stress Test: arm64 macos monterey [cd] [release]"

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 Makefile` `md5 CMakeLists.txt` `md5 lib/CMakeLists.txt` arm64 ghcr.io/cirruslabs/macos-ventura-xcode:14.3 20220511"
    populate_script: make libs build_flags=-j12
  upload_caches:
    - libs

  configure_script:
    - make configure arch=armv8 config=debug
  build_script:
    - make build config=debug
  stress_test_script:
    - make ${TARGET} config=debug usedebugger=lldb

task:
  only_if: $CIRRUS_CRON == "stress"

  timeout_in: 120m

  windows_container:
    image: ponylang/ponyc-ci-x86-64-pc-windows-msvc-builder:20220803
    os_version: 2019
    cpu: 8
    memory: 24

  matrix:
    - name: "Stress Test: x86-64 Windows [release]"
      environment:
        TARGET: stress-test-release
    - name: "Stress Test: x86-64 Windows [debug]"
      environment:
        TARGET: stress-test-debug
      depends_on:
        - "Stress Test: x86-64 Windows [release]"
    - name: "Stress Test: x86-64 Windows [cd] [release]"
      environment:
        TARGET: stress-test-with-cd-release
    - name: "Stress Test: x86-64 Windows [cd] [debug]"
      environment:
        TARGET: stress-test-with-cd-debug
      depends_on:
        - "Stress Test: x86-64 Windows [cd] [release]"

  libs_cache:
    folder: build/libs
    fingerprint_script:
      - ps: (Get-FileHash -Path make.ps1).Hash + (Get-FileHash -Path CMakeLists.txt).Hash + (Get-FileHash -Path lib\CMakeLists.txt).Hash + "Windows 20220803"
    populate_script:
      - ps: .\make.ps1 -Command libs -Generator "Visual Studio 17 2022"
  upload_caches:
    - libs

  configure_script:
    - ps: .\make.ps1 -Command configure -Config Debug -Generator "Visual Studio 17 2022"
  build_script:
    - ps: .\make.ps1 -Command build -Config Debug
  stress_test_script:
    - ps: .\make.ps1 -Command $env:TARGET -Config Debug
