task:
  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191105
    cpu: 8
    memory: 24

  name: "lib/llvm: x86-64-unknown-linux-gnu"

  clone_script: |
    if [ -z "$CIRRUS_PR" ]; then
      git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    else
      git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    fi

  test_script:
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release -j8
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release test-ci

  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release'

task:
  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20191105
    cpu: 8
    memory: 24

  name: "lib/llvm: x86-64-unknown-linux-musl"

  clone_script: |
    if [ -z "$CIRRUS_PR" ]; then
      git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    else
      git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    fi

  test_script:
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release link=static -j8
    - make -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release link=static test-ci

  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release'

task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
    cpu: 8
    memory: 24

  name: "lib/llvm: x86-64-unknown-freebsd12"

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y cmake gmake libunwind git

  clone_script: |
    if [ -n "$CIRRUS_TAG" ]
    then
      echo "cloning for tag $CIRRUS_TAG"
      git clone --depth 1 --branch "$CIRRUS_TAG" --recurse-submodules https://github.com/ponylang/ponyc.git
    elif [ -n "$CIRRUS_BRANCH" ]
    then
      echo "cloning for branch $CIRRUS_BRANCH"
      git clone --depth 1 --branch "$CIRRUS_BRANCH" --recurse-submodules https://github.com/ponylang/ponyc.git
    fi

  test_script:
    - cc --version
    - c++ --version
    - cd ponyc
    - gmake -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release -j8
    - gmake -f Makefile-lib-llvm default_pic=true arch=x86-64 config=release test-ci

  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release'

task:
  osx_instance:
    image: mojave-xcode-11.1

  name: "macOS"

  install_script:
    - curl -o macports.pkg https://distfiles.macports.org/MacPorts/MacPorts-2.6.0-10.14-Mojave.pkg
    - sudo installer -verbose -pkg macports.pkg -target /
    - sudo /opt/local/bin/port selfupdate
    - sudo /opt/local/bin/port install llvm-7.0

  test_script:
    - export LDFLAGS="-L/opt/local/lib"
    - export PATH=/usr/local/opt/llvm/bin/:$PATH
    - export CC1=clang
    - export CXX1=clang++
    - export LLVM_CONFIG=/opt/local/bin/llvm-config-mp-7.0
    - make LLVM_CONFIG="$LLVM_CONFIG" CC="$CC1" CXX="$CXX1" -j$(sysctl -n hw.ncpu) config=release all
    - make LLVM_CONFIG="$LLVM_CONFIG" CC="$CC1" CXX="$CXX1" config=release test-ci

  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release'
