version: 2
jobs:
  verify-changelog:
    docker:
      - image: ponylang/changelog-tool:release
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get -y install curl
      - run: changelog-tool verify CHANGELOG.md
      - run: *notify

  validate-shell-scripts:
    docker:
      - image: ponylang/ponyc-ci:shellcheck
    steps:
      - checkout
      - run: find . -name '*.bash' -exec shellcheck {} \;
      - run: *notify

workflows:
  version: 2
  tests:
    jobs:
      # sanity tests
      - verify-changelog
      - validate-shell-scripts

commands:
  approval:
    description: Send a notification that a manual approval job is ready
    parameters:
      color:
        default: '#3AA3E3'
        description: Hex color value for notification attachment color.
        type: string
      mentions:
        default: ""
        description: A comma separated list of user IDs. No spaces.
        type: string
      message:
        default: A workflow in CircleCI is awaiting your approval.
        description: Enter custom message.
        type: string
      url:
        default: https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}
        description: The URL to link back to.
        type: string
      webhook:
        default: ${ZULIP_WEBHOOK}
        description: Enter either your Webhook value or use the CircleCI UI to add
          your token under the 'ZULIP_WEBHOOK' env var
        type: string
    steps:
    - run:
        command: |
          if [ -z "$BASH" ]; then
            echo Bash not installed.
            exit 1
          fi
        name: Provide error if non-bash shell
    - run:
        command: |
          # Provide error if non-bash shell
          if [ -z "$BASH" ]; then
            echo Bash not installed.
            exit 1
          fi
          # Provide error if no webhook is set and error. Otherwise continue
          if [ -z "<< parameters.webhook >>" ]; then
            echo "NO ZULIP WEBHOOK SET"
            echo "Please input your ZULIP_WEBHOOK value either in the settings for this project, or as a parameter for this orb."
            exit 1
          else
            #Create Members string
            if [ -n "<< parameters.mentions >>" ]; then
              IFS="," read -ra ZULIP_MEMBERS \<<< "<< parameters.mentions >>"
              for i in "${ZULIP_MEMBERS[@]}"; do
                if [ $(echo ${i} | head -c 1) == "S" ]; then
                  ZULIP_MENTIONS="${ZULIP_MENTIONS}<!subteam^${i}> "
                elif echo ${i} | grep -E "^(here|channel|everyone)$" > /dev/null; then
                  ZULIP_MENTIONS="${ZULIP_MENTIONS}<!${i}> "
                else
                  ZULIP_MENTIONS="${ZULIP_MENTIONS}<@${i}> "
                fi
              done
            fi

            curl -X POST -H 'Content-type: application/json' \
              --data \
              "{ \
                \"attachments\": [ \
                  { \
                    \"fallback\": \"<< parameters.message >> - << parameters.url >>\", \
                    \"text\": \"<< parameters.message >> $ZULIP_MENTIONS\", \
                    \"fields\": [ \
                      { \
                        \"title\": \"Project\", \
                        \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
                        \"short\": true \
                      }, \
                      { \
                        \"title\": \"Job Number\", \
                        \"value\": \"$CIRCLE_BUILD_NUM\", \
                        \"short\": true \
                      } \
                    ], \
                    \"actions\": [ \
                      { \
                        \"type\": \"button\", \
                        \"text\": \"Visit Workflow\", \
                        \"url\": \"<< parameters.url >>\" \
                      } \
                    ], \
                    \"color\": \"<< parameters.color >>\" \
                  } \
                ] \
              }" << parameters.webhook >>
            echo "Awaiting approval notified."
          fi
        name: Zulip - Sending Approval Notification
        shell: /bin/bash
  notify:
    description: Notify a Zulip stream with a custom message
    parameters:
      author_link:
        default: ""
        description: Optional author link
        type: string
      author_name:
        default: ""
        description: Optional author name
        type: string
      color:
        default: '#333333'
        description: Hex color value for notification attachment color.
        type: string
      footer:
        default: ""
        description: Optional footer
        type: string
      include_job_number_field:
        default: true
        description: Whether or not to include the Job Number field in the message
        type: boolean
      include_project_field:
        default: true
        description: Whether or not to include the Project field in the message
        type: boolean
      include_visit_job_action:
        default: true
        description: Whether or not to include the Visit Job action in the message
        type: boolean
      mentions:
        default: ""
        description: A comma separated list of user IDs. No spaces.
        type: string
      message:
        default: Your job on CircleCI has completed.
        description: Enter custom message.
        type: string
      title:
        default: ""
        description: Optional title
        type: string
      title_link:
        default: ""
        description: Optional title link
        type: string
      ts:
        default: ""
        description: Optional timestamp
        type: string
      webhook:
        default: ${ZULIP_WEBHOOK}
        description: Enter either your Webhook value or use the CircleCI UI to add
          your token under the 'ZULIP_WEBHOOK' env var
        type: string
    steps:
    - run:
        command: |
          if [ -z "$BASH" ]; then
            echo Bash not installed.
            exit 1
          fi
        name: Provide error if non-bash shell
    - run:
        command: |
          # Provide error if no webhook is set and error. Otherwise continue
          if [ -z "<< parameters.webhook >>" ]; then
            echo "NO ZULIP WEBHOOK SET"
            echo "Please input your ZULIP_WEBHOOK value either in the settings for this project, or as a parameter for this orb."
            exit 1
          else
            # Webhook properly set.
            echo Notifying Zulip stream
            #Create Members string
            if [ -n "<< parameters.mentions >>" ]; then
              IFS="," read -ra ZULIP_MEMBERS \<<< "<< parameters.mentions >>"
              for i in "${ZULIP_MEMBERS[@]}"; do
                if [ $(echo ${i} | head -c 1) == "S" ]; then
                  ZULIP_MENTIONS="${ZULIP_MENTIONS}<!subteam^${i}> "
                elif echo ${i} | grep -E "^(here|channel|everyone)$" > /dev/null; then
                  ZULIP_MENTIONS="${ZULIP_MENTIONS}<!${i}> "
                else
                  ZULIP_MENTIONS="${ZULIP_MENTIONS}<@${i}> "
                fi
              done
            fi
            # Build up our content string. Everything in the here doc between
            # 'EOF's will be sent
            IFS='' read -r -d '' Content <<"EOF"
              $CIRCLE_PROJECT_REPONAME build status
            EOF
            # Send it!
            curl -X POST << parameters.webhook >>\
              -u pony-circleci-bot@ponylang.zulipchat.com:57HRshi7qDYxJvAib8LzbCFTT32foDHh \
              -d "type=stream" \
              -d "to=zulip" \
              -d "topic: test from zulip-orb" \
              -d "content=${Content}"

              # --data \
              # "{ \
              #   \"attachments\": [ \
              #     { \
              #       \"fallback\": \"<< parameters.message >> - $CIRCLE_BUILD_URL\", \
              #       \"text\": \"<< parameters.message >> $ZULIP_MENTIONS\", \
              #       \"author_name\": \"<< parameters.author_name >>\", \
              #       \"author_link\": \"<< parameters.author_link >>\", \
              #       \"title\": \"<< parameters.title >>\", \
              #       \"title_link\": \"<< parameters.title_link >>\", \
              #       \"footer\": \"<< parameters.footer >>\", \
              #       \"ts\": \"<< parameters.ts >>\", \
              #       \"fields\": [ \
              #         <<# parameters.include_project_field >>
              #         { \
              #           \"title\": \"Project\", \
              #           \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
              #           \"short\": true \
              #         }, \
              #         <</ parameters.include_project_field >>
              #         <<# parameters.include_job_number_field >>
              #         { \
              #           \"title\": \"Job Number\", \
              #           \"value\": \"$CIRCLE_BUILD_NUM\", \
              #           \"short\": true \
              #         } \
              #         <</ parameters.include_job_number_field >>
              #       ], \
              #       \"actions\": [ \
              #         <<# parameters.include_visit_job_action >>
              #         { \
              #           \"type\": \"button\", \
              #           \"text\": \"Visit Job\", \
              #           \"url\": \"$CIRCLE_BUILD_URL\" \
              #         } \
              #         <</ parameters.include_visit_job_action >>
              #       ], \
              #       \"color\": \"<< parameters.color >>\" \
              #     } \
              #   ] \
              # }" << parameters.webhook >>
          fi
        name: Zulip Notification
        shell: /bin/bash
  notify-on-failure:
    description: |
      A handy command to notify a Zulip stream on failure in the default master branch
    parameters:
      only_for_branches:
        default: ""
        description: |
          If set, a comma-separated list of branches for which to send notifications. No spaces.
        type: string
    steps:
    - status:
        fail_only: true
        only_for_branches: <<parameters.only_for_branches>>
  status:
    description: |
      Send a status alert at the end of a job based on success or failure. Must be the last step in a job.
    parameters:
      fail_only:
        default: false
        description: |
          If `true`, notifications successful jobs will not be sent
        type: boolean
      failure_message:
        default: ':red_circle: A $CIRCLE_JOB job has failed!'
        description: Enter custom message.
        type: string
      include_job_number_field:
        default: true
        description: |
          Whether or not to include the Job Number field in the message
        type: boolean
      include_project_field:
        default: true
        description: |
          Whether or not to include the Project field in the message
        type: boolean
      include_visit_job_action:
        default: true
        description: |
          Whether or not to include the Visit Job action in the message
        type: boolean
      mentions:
        default: ""
        description: |
          A comma separated list of user IDs. No spaces.
        type: string
      only_for_branches:
        default: ""
        description: |
          If set, a comma-separated list of branches for which to send notifications. No spaces.
        type: string
      success_message:
        default: ':tada: A $CIRCLE_JOB job has succeeded!'
        description: Enter custom message.
        type: string
      webhook:
        default: ${ZULIP_WEBHOOK}
        description: |
          Enter either your Webhook value or use the CircleCI UI to add your token under the 'ZULIP_WEBHOOK' env var
        type: string
    steps:
    - run:
        command: |
          echo 'export ZULIP_BUILD_STATUS="fail"' >> $BASH_ENV
        name: Zulip - Setting Failure Condition
        when: on_fail
    - run:
        command: |
          echo 'export ZULIP_BUILD_STATUS="success"' >> $BASH_ENV
        name: Zulip - Setting Success Condition
        when: on_success
    - run:
        command: |
          if [ -z "$BASH" ]; then
            echo Bash not installed.
            exit 1
          fi
        name: Provide error if non-bash shell
    - run:
        command: |
          current_branch_in_filter=false

          IFS="," read -ra BRANCH_FILTERS \<<< "<< parameters.only_for_branches >>"

          for i in "${BRANCH_FILTERS[@]}"; do
            if [ "${i}" == "${CIRCLE_BRANCH}" ]; then
              current_branch_in_filter=true
            fi
          done

          if [ "x" == "x<< parameters.only_for_branches>>" ] || [ "$current_branch_in_filter" = true ]; then
            # Provide error if no webhook is set and error. Otherwise continue
            if [ -z "<< parameters.webhook >>" ]; then
              echo "NO ZULIP WEBHOOK SET"
              echo "Please input your ZULIP_WEBHOOK value either in the settings for this project, or as a parameter for this orb."
              exit 1
            else
              #Create Members string
              if [ -n "<< parameters.mentions >>" ]; then
                IFS="," read -ra ZULIP_MEMBERS \<<< "<< parameters.mentions >>"
                for i in "${ZULIP_MEMBERS[@]}"; do
                  if [ $(echo ${i} | head -c 1) == "S" ]; then
                    ZULIP_MENTIONS="${ZULIP_MENTIONS}<!subteam^${i}> "
                  elif echo ${i} | grep -E "^(here|channel|everyone)$" > /dev/null; then
                    ZULIP_MENTIONS="${ZULIP_MENTIONS}<!${i}> "
                  else
                    ZULIP_MENTIONS="${ZULIP_MENTIONS}<@${i}> "
                  fi
                done
              fi
              #If successful
              if [ "$ZULIP_BUILD_STATUS" = "success" ]; then
                #Skip if fail_only
                if [ << parameters.fail_only >> = true ]; then
                  echo "The job completed successfully"
                  echo '"fail_only" is set to "true". No Zulip Notification sent.'
                else
                  curl -X POST -H 'Content-type: application/json' \
                    --data "{ \
                              \"attachments\": [ \
                                { \
                                  \"fallback\": \"<< parameters.success_message >>\", \
                                  \"text\": \"<< parameters.success_message >> $ZULIP_MENTIONS\", \
                                  \"fields\": [ \
                                    <<# parameters.include_project_field >>
                                    { \
                                      \"title\": \"Project\", \
                                      \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
                                      \"short\": true \
                                    }, \
                                    <</ parameters.include_project_field >>
                                    <<# parameters.include_job_number_field >>
                                    { \
                                      \"title\": \"Job Number\", \
                                      \"value\": \"$CIRCLE_BUILD_NUM\", \
                                      \"short\": true \
                                    } \
                                    <</ parameters.include_job_number_field >>
                                  ], \
                                  \"actions\": [ \
                                    <<# parameters.include_visit_job_action >>
                                    { \
                                      \"type\": \"button\", \
                                      \"text\": \"Visit Job\", \
                                      \"url\": \"$CIRCLE_BUILD_URL\" \
                                    } \
                                    <</ parameters.include_visit_job_action >>
                                  ], \
                                  \"color\": \"#1CBF43\" \
                                } \
                              ] \
                            } " << parameters.webhook >>
                  echo "Job completed successfully. Alert sent."
                fi
              else
                #If Failed
                curl -X POST -H 'Content-type: application/json' \
                  --data "{ \
                    \"attachments\": [ \
                      { \
                        \"fallback\": \"<< parameters.failure_message >>\", \
                        \"text\": \"<< parameters.failure_message >> $ZULIP_MENTIONS\", \
                        \"fields\": [ \
                          <<# parameters.include_project_field >>
                          { \
                            \"title\": \"Project\", \
                            \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
                            \"short\": true \
                          }, \
                          <</ parameters.include_project_field >>
                          <<# parameters.include_job_number_field >>
                          { \
                            \"title\": \"Job Number\", \
                            \"value\": \"$CIRCLE_BUILD_NUM\", \
                            \"short\": true \
                          } \
                          <</ parameters.include_job_number_field >>
                        ], \
                        \"actions\": [ \
                          <<# parameters.include_visit_job_action >>
                          { \
                            \"type\": \"button\", \
                            \"text\": \"Visit Job\", \
                            \"url\": \"$CIRCLE_BUILD_URL\" \
                          } \
                          <</ parameters.include_visit_job_action >>
                        ], \
                        \"color\": \"#ed5c5c\" \
                      } \
                    ] \
                  } " << parameters.webhook >>
                echo "Job failed. Alert sent."
              fi
            fi
          else
            echo "Current branch is not included in only_for_branches filter; no status alert will be sent"
          fi
        name: Zulip - Sending Status Alert
        shell: /bin/bash
        when: always


