version: 2.1

jobs:
  alpine-vendored:
    docker:
      - image:  alpine
    steps:
      - run: apk add --update alpine-sdk libexecinfo-dev binutils-gold coreutils linux-headers zlib-dev ncurses-dev
      - run: apk add --update cmake cmake-doc extra-cmake-modules extra-cmake-modules-doc
      - checkout
      - run: make test-ci -f Makefile-lib-llvm default_pic=true -j4

workflows:
  version: 2.1
  tests:
    jobs:
      - alpine-vendored:
          context: org-global
 