version: 2
jobs:
  verify-changelog:
    docker:
      - image: ponylang/changelog-tool:release
    steps:
      - checkout
      - run: changelog-tool verify CHANGELOG.md
  validate-docker-image-builds:
      docker:
        - image: docker:17.05.0-ce-git
      steps:
        - checkout
        - setup_remote_docker
        - run: docker build --cache-from=app -t app .
  validate-shell-scripts:
    docker:
      - image: ponylang/ponyc-ci:shellcheck
    steps:
      - checkout
      - run: find . -name '*.bash' -exec shellcheck {} \;
  ubuntu-llvm-600-debug:
    docker:
      - image: ponylang/ponyc-ci:ubuntu
        user: pony
    steps:
      - checkout
      - run: make test-ci config=debug default_pic=true llvm_proj=llvm-6.0.0
  ubuntu-llvm-600-release:
    docker:
      - image: ponylang/ponyc-ci:ubuntu
        user: pony
    steps:
      - checkout
      - run: make test-ci config=release default_pic=true llvm_proj=llvm-6.0.0
  ubuntu-debug:
    docker:
      - image: ponylang/ponyc-ci:ubuntu
        user: pony
    steps:
      - checkout
      - run: make test-ci config=debug default_pic=true llvm_proj=llvm-3.9.1
  ubuntu-release:
    docker:
      - image: ponylang/ponyc-ci:ubuntu
        user: pony
    steps:
      - checkout
      - run: make test-ci config=release default_pic=true llvm_proj=llvm-3.9.1
  ubuntu-openssl-110:
    docker:
      - image: ponylang/ponyc-ci:ubuntu-openssl_1.1.0
        user: pony
    steps:
      - checkout
      - run: make test-ci default_ssl=openssl_1.1.0 default_pic=true
  alpine-debug:
    docker:
      - image: ponylang/ponyc-ci:alpine
        user: pony
    steps:
      - checkout
      - run: make test-ci verbose=1 config=debug default_pic=true llvm_proj=llvm-3.9.1
  alpine-release:
    docker:
      - image: ponylang/ponyc-ci:alpine
        user: pony
    steps:
      - checkout
      - run: make test-ci verbose=1 config=release default_pic=true llvm_proj=llvm-3.9.1
  alpine-llvm-600-release:
    docker:
      - image: ponylang/ponyc-ci:alpine
        user: pony
    steps:
      - checkout
      - run: make test-ci verbose=1 config=release default_pic=true llvm_proj=llvm-6.0.0
  centos7-debug:
    docker:
      - image: ponylang/ponyc-ci:centos7
        user: pony
    steps:
      - checkout
      - run: make test-ci config=debug default_pic=true use="llvm_link_static" llvm_proj=llvm-3.9.1
  centos7-release:
    docker:
      - image: ponylang/ponyc-ci:centos7
        user: pony
    steps:
      - checkout
      - run: make test-ci config=release default_pic=true use="llvm_link_static" llvm_proj=llvm-3.9.1
  centos7-llvm-600-release:
    docker:
      - image: ponylang/ponyc-ci:centos7
        user: pony
    steps:
      - checkout
      - run: make test-ci config=release default_pic=true use="llvm_link_static" llvm_proj=llvm-6.0.0

workflows:
  version: 2
  tests:
    jobs:
      - verify-changelog
      - validate-shell-scripts
      - validate-docker-image-builds
      - ubuntu-llvm-600-debug
      - ubuntu-llvm-600-release
      - ubuntu-debug
      - ubuntu-release
      - ubuntu-openssl-110
      #- alpine-debug
      #- alpine-release
      - alpine-llvm-600-release
      - centos7-debug
      - centos7-release
      - centos7-llvm-600-release
