version: 2.1

orbs:
    zulip: ponylang/zulip@dev:first

jobs:
  verify-changelog:
    docker:
      - image: ponylang/changelog-tool:release
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get -y install curl
      - run: changelog-tool verify CHANGELOG.md
      - zulip/notify:
          message: "This is a custom message notification"

  validate-shell-scripts:
    docker:
      - image: ponylang/ponyc-ci:shellcheck
    steps:
      - checkout
      - run: find . -name '*.bash' -exec shellcheck {} \;
      - zulip/notify:
          message: "This is a custom message notification"

workflows:
  version: 2.1
  tests:
    jobs:
      # sanity tests
      - verify-changelog
      - validate-shell-scripts
