version: 2
jobs:
  verify-changelog:
    docker:
      - image: ponylang/changelog-tool:release
    steps:
      - checkout
      - run: apt-get -y install curl
      - run: changelog-tool verify CHANGELOG.md
      - run:
          name: Failure notification
          command: bash .ci-scripts/notify-zulip-on-circleci-failure.bash
          when: on_fail

  validate-shell-scripts:
    docker:
      - image: ponylang/ponyc-ci:shellcheck
    steps:
      - checkout
      - run: apt-get -y install curl
      - run: find . -name '*.bash' -exec shellcheck {} \;
      - run:
          name: Failure notification
          command: bash .ci-scripts/notify-zulip-on-circleci-failure.bash
          when: on_fail

workflows:
  version: 2
  tests:
    jobs:
      # sanity tests
      - verify-changelog
      - validate-shell-scripts