name: Handle external events

on: repository_dispatch

jobs:
  log-external-event:
    name: Log all incoming events
    runs-on: ubuntu-latest
    steps:
      - name: Log event
        run: echo "$EVENT"
        env:
          EVENT: ${{ toJson(github.event) }}

  build-latest-gnu-docker-image:
    if: |
      github.event.action == 'cloudsmith-package-synchronised' &&
      github.event.client_payload.data.repository == 'nightlies' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-unknown-linux-ubuntu20.04.tar.gz'

    name: Build latest GNU Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .dockerfiles/latest/x86-64-unknown-linux-gnu/build-and-push.bash

  build-latest-musl-docker-image:
    if: |
      github.event.action == 'cloudsmith-package-synchronised' &&
      github.event.client_payload.data.repository == 'nightlies' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-unknown-linux-musl.tar.gz'

    name: Build latest musl Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .dockerfiles/latest/x86-64-unknown-linux-musl/build-and-push.bash

  build-latest-windows-docker-image:
    if: |
      github.event.action == 'cloudsmith-package-synchronised' &&
      github.event.client_payload.data.repository == 'nightlies' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-pc-windows-msvc.zip'

    name: Build latest Windows Docker image
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $env:DOCKER_USERNAME -p $env:DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: .dockerfiles/latest/x86-64-pc-windows-msvc/build-and-push.ps1

  build-release-gnu-docker-image:
    if: |
      github.event.action == 'cloudsmith-package-synchronised' &&
      github.event.client_payload.data.repository == 'releases' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-unknown-linux-ubuntu20.04.tar.gz'

    name: Build release GNU Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .dockerfiles/release/x86-64-unknown-linux-gnu/build-and-push.bash
        env:
          VERSION: ${{ github.event.client_payload.data.version }}

  build-release-musl-docker-image:
    if: |
      github.event.action == 'cloudsmith-package-synchronised' &&
      github.event.client_payload.data.repository == 'releases' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-unknown-linux-musl.tar.gz'

    name: Build release musl Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .dockerfiles/release/x86-64-unknown-linux-musl/build-and-push.bash
        env:
          VERSION: ${{ github.event.client_payload.data.version }}

  build-release-windows-docker-image:
    if: |
      github.event.action == 'cloudsmith-package-synchronised' &&
      github.event.client_payload.data.repository == 'releases' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-pc-windows-msvc.zip'

    name: Build release Windows Docker image
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $env:DOCKER_USERNAME -p $env:DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: .dockerfiles/release/x86-64-pc-windows-msvc/build-and-push.ps1
        env:
          VERSION: ${{ github.event.client_payload.data.version }}

  update-playground-image-on-release:
    needs: build-release-musl-docker-image

    name: Update https://playground.ponylang.io/
    runs-on: ubuntu-latest
    steps:
      - name: Run remote command
        uses: appleboy/ssh-action@ffff33f8fe0318345a4f00f0e847325954b2a3ed
        with:
          host: ${{ secrets.PLAYGROUND_HOST }}
          username: ${{ secrets.PLAYGROUND_ADMIN_USER }}
          key: ${{ secrets.PLAYGROUND_KEY }}
          script: bash update-playground.bash

  update-stdlib-builder-image-on-release:
    needs: build-release-musl-docker-image

    name: Updates stdlib-builder Docker image with newly released ponyc version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .ci-dockerfiles/stdlib-builder/build-and-push.bash

  update-stdlib-builder-image-on-nightly:
    needs: build-latest-musl-docker-image

    name: Updates stdlib-builder Docker image with nightly ponyc version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .ci-dockerfiles/stdlib-builder/build-and-push.bash

  build-and-push-stdlib-documentation:
    needs: update-stdlib-builder-image-on-release

    name: Build and Push standard library documentation
    runs-on: ubuntu-latest
    container:
      image: ponylang/ponyc-ci-stdlib-builder:release
    steps:
      - uses: actions/checkout@v1
      - name: Build and push
        run: "bash .ci-scripts/build-and-push-stdlib-documentation.bash $STDLIB_TOKEN"
        env:
          STDLIB_TOKEN: ${{ secrets.STDLIB_TOKEN }}

  trigger-release-announcement:
    name: Trigger release announcement
    runs-on: ubuntu-latest
    needs: [build-and-push-stdlib-documentation, update-playground-image-on-release]
    steps:
      - uses: actions/checkout@v1
      - name: Trigger
        uses: ponylang/release-bot-action@0.3.3
        with:
          step: trigger-release-announcement
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          VERSION: ${{ github.event.client_payload.data.version }}
