name: Nightlies

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  x86_64-Linux-glibc:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu22.04-builder:20230806
            name: x86-64-unknown-linux-ubuntu22.04
            triple-os: linux-ubuntu22.04
            triple-vendor: unknown
          - image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu20.04-builder:20230807
            name: x86-64-unknown-linux-ubuntu20.04
            triple-os: linux-ubuntu20.04
            triple-vendor: unknown

    name: ${{ matrix.name }}
    container:
      image: ${{ matrix.image }}
      options: --user pony

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Libs
        id: cache-libs
        uses: actions/cache@v3
        env:
          cache-name: libs
        with:
          path: build/libs
          key: ${{ env.cache-name }}-${{ matrix.image }}-${{ hashFiles('Makefile', 'CMakeLists.txt', 'libs/CMakeLists.txt') }}
      - name: Build Libs
        if: steps.cache-libs.outputs.cache-hit != 'true'
        run: make libs build_flags=-j4
      - name: Nightly
        run: bash .ci-scripts/x86-64-nightly.bash
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
          TRIPLE_VENDOR: ${{ matrix.triple-vendor }}
          TRIPLE_OS: ${{ matrix.triple-os }}
