name: Nightlies

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  x86_64-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu22.04-builder:20230806
            name: x86-64-unknown-linux-ubuntu22.04
            triple-os: linux-ubuntu22.04
            triple-vendor: unknown
          - image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu20.04-builder:20230807
            name: x86-64-unknown-linux-ubuntu20.04
            triple-os: linux-ubuntu20.04
            triple-vendor: unknown
          - image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20230808
            name: x86-64-unknown-linux-musl
            triple-os: linux-musl
            triple-vendor: unknown

    name: ${{ matrix.name }}
    container:
      image: ${{ matrix.image }}
      options: --user pony

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore Libs Cache
        id: restore-libs
        uses: actions/cache/restore@v3
        with:
          path: build/libs
          key: libs-${{ matrix.image }}-${{ hashFiles('Makefile', 'CMakeLists.txt', 'libs/CMakeLists.txt') }}
      - name: Build Libs
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: make libs build_flags=-j8
      - name: Save Libs Cache
        if: steps.restore-libs.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: build/libs
          key: libs-${{ matrix.image }}-${{ hashFiles('Makefile', 'CMakeLists.txt', 'libs/CMakeLists.txt') }}
      - name: Nightly
        run: bash .ci-scripts/x86-64-nightly.bash
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
          TRIPLE_VENDOR: ${{ matrix.triple-vendor }}
          TRIPLE_OS: ${{ matrix.triple-os }}
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ github.job }}  failed.

  x86_macos:
    runs-on: macos-13

    name: x86-64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore Libs Cache
        id: restore-libs
        uses: actions/cache/restore@v3
        with:
          path: build/libs
          key: libs-x86-macos-13-${{ hashFiles('Makefile', 'CMakeLists.txt', 'libs/CMakeLists.txt') }}
      - name: Build Libs
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: make libs build_flags=-j8
      - name: Save Libs Cache
        if: steps.restore-libs.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: build/libs
          key: libs-x86-macos-13-${{ hashFiles('Makefile', 'CMakeLists.txt', 'libs/CMakeLists.txt') }}
      - name: Install Dependencies
        run: |
          brew install python
          pip3 install --upgrade cloudsmith-cli
      - name: Nightly
        run: bash .ci-scripts/x86-64-nightly.bash
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
          TRIPLE_VENDOR: apple
          TRIPLE_OS: darwin
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ github.job }}  failed.
