name: PR

on: pull_request

jobs:
  superlinter:
    name: Lint bash, docker, markdown, and yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_MD: true
          VALIDATE_YAML: true

  validate-musl-docker-latest-image-builds:
    name: Validate musl Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull --file=.dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile ."

  validate-gnu-docker-latest-image-builds:
    name: Validate GNU Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull --file=.dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile ."

  validate-windows-docker-latest-image-builds:
    name: Validate Windows Docker image builds
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull .dockerfiles/latest/x86-64-pc-windows-msvc"

  validate-musl-docker-release-image-builds:
    name: Validate musl Docker release image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull --file=.dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile ."

  validate-gnu-docker-release-image-builds:
    name: Validate GNU Docker release image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull --file=.dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile ."

  validate-windows-docker-release-image-builds:
    name: Validate Windows Docker release image builds
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull .dockerfiles/release/x86-64-pc-windows-msvc"

  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v2
      - name: Verify CHANGELOG
        run: changelog-tool verify

  x86_64-Linux-glibc:
    name: x86-64 Linux glibc
    runs-on: ubuntu-latest
    container:
      image: ponylang/ponyc-ci-x86-64-unknown-linux-ubuntu22.04-builder-gh:20230805
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Git Fuckery
        run: git config --global --add safe.directory /__w/ponyc/ponyc
      - name: Libs
        run: make libs build_flags=-j4
      - name: Debug Configure
        run: make configure arch=x86-64 config=debug
      - name: Debug Build
        run: make build config=debug
      - name: Debug Test
        run: make test-ci config=debug
      - name: Release Configure
        run: make configure arch=x86-64 config=release
      - name: Release Build
        run: make build config=release
      - name: Release Test
        run: make test-ci config=release
