name: PR

on: pull_request

jobs:
  clang-gnu:
    name: Clang GNU
    runs-on: ubuntu-latest
    container:
      image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191106
    steps:
      - uses: actions/checkout@v1
      - name: clang?
        run: clang --version

  clang-musl:
    name: Clang Musl
    runs-on: ubuntu-latest
    container:
      image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20191106
    steps:
      - uses: actions/checkout@v1
      - name: clang?
        run: clang --version
