name: Release

on:
  push:
    tags:
      - \d+.\d+.\d+

jobs:
  build-and-push-stdlib-documentation:
    name: Build and Push standard library documentation
    runs-on: ubuntu-latest
    container:
      image: ponylang/ponyc-ci-stdlib-builder:latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and push
        run: "bash .ci-scripts/build-and-push-stdlib-documentation $STDLIB_TOKEN"
        env:
          STDLIB_TOKEN: ${{ secrets.STDLIB_TOKEN }}

  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@eb843fa04b91b8bc5d4953899e3fff15c95f347c
        with:
          formula-name: ponyc
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_RELEASE_TOKEN }
