name: Trigger nightly builds

on:
  schedule:
    - cron: "15 0 * * *"

jobs:
  trigger-nightly-builds-on-cirrusci:
    name: Trigger nightly builds on CirrusCI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Send curl request
        run: bash trigger-nightly-builds.bash
        env:
          CIRRUS_ACCESS_TOKEN: ${{ secrets.CIRRUS_ACCESS_TOKEN }}
